const FETCH_LATEST_MOVIES_REQUEST = 'FETCH_LATEST_MOVIES_REQUEST';
const FETCH_LATEST_MOVIES_SUCCESS = 'FETCH_LATEST_MOVIES_SUCCESS';
const FETCH_LATEST_MOVIES_FAILURE = 'FETCH_LATEST_MOVIES_FAILURE';

const FETCH_TOPRATED_MOVIES_REQUEST = 'FETCH_TOPRATED_MOVIES_REQUEST';
const FETCH_TOPRATED_MOVIES_SUCCESS = 'FETCH_TOPRATED_MOVIES_SUCCESS';
const FETCH_TOPRATED_MOVIES_FAILURE = 'FETCH_TOPRATED_MOVIES_FAILURE';

const FETCH_UPCOMING_MOVIES_REQUEST = 'FETCH_UPCOMING_MOVIES_REQUEST';
const FETCH_UPCOMING_MOVIES_SUCCESS = 'FETCH_UPCOMING_MOVIES_SUCCESS';
const FETCH_UPCOMING_MOVIES_FAILURE = 'FETCH_UPCOMING_MOVIES_FAILURE';

const FETCH_MOVIES_BY_GENRE_REQUEST = 'FETCH_MOVIES_BY_GENRE_REQUEST';
const FETCH_MOVIES_BY_GENRE_SUCCESS = 'FETCH_MOVIES_BY_GENRE_SUCCESS';
const FETCH_MOVIES_BY_GENRE_FAILURE = 'FETCH_MOVIES_BY_GENRE_FAILURE';

const FETCH_SEARCH_MOVIES_REQUEST = 'FETCH_SEARCH_MOVIES_REQUEST';
const FETCH_SEARCH_MOVIES_SUCCESS = 'FETCH_SEARCH_MOVIES_SUCCESS';
const FETCH_SEARCH_MOVIES_FAILURE = 'FETCH_SEARCH_MOVIES_FAILURE';

const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';

const FETCH_VIDEO_KEY_REQUEST = 'FETCH_VIDEO_KEY_REQUEST';
const FETCH_VIDEO_KEY_SUCCESS = 'FETCH_VIDEO_KEY_SUCCESS';
const FETCH_VIDEO_KEY_FAILURE = 'FETCH_VIDEO_KEY_FAILURE';

const CHANGE_FILTER = 'CHANGE_FILTER';

export {
  FETCH_LATEST_MOVIES_REQUEST, FETCH_LATEST_MOVIES_SUCCESS, FETCH_LATEST_MOVIES_FAILURE,
  FETCH_TOPRATED_MOVIES_REQUEST, FETCH_TOPRATED_MOVIES_SUCCESS, FETCH_TOPRATED_MOVIES_FAILURE,
  FETCH_UPCOMING_MOVIES_REQUEST, FETCH_UPCOMING_MOVIES_SUCCESS, FETCH_UPCOMING_MOVIES_FAILURE,
  FETCH_MOVIES_BY_GENRE_REQUEST, FETCH_MOVIES_BY_GENRE_SUCCESS, FETCH_MOVIES_BY_GENRE_FAILURE,
  FETCH_SEARCH_MOVIES_REQUEST, FETCH_SEARCH_MOVIES_SUCCESS, FETCH_SEARCH_MOVIES_FAILURE,
  FETCH_GENRES_REQUEST, FETCH_GENRES_SUCCESS, FETCH_GENRES_FAILURE,
  FETCH_VIDEO_KEY_REQUEST, FETCH_VIDEO_KEY_SUCCESS, FETCH_VIDEO_KEY_FAILURE,
  CHANGE_FILTER,
};
